---
language: bash
dist: xenial
sudo: false

before_install:
  - apt-get update

install:
  - make init

before_script:
  - make lint check-migrate

script:
  - make no-skip test

addons:
  apt:
    update: true
